const Data = [
    {
      id: 1,
      category: "education",
      icon: "icon-graduation",
      year: "2020 - 2024",
      title: "Bachelor of Technology ",
      major: "Major: Computer Science Engineering",
      grade: "CGPA: 8.68/10.0",
      college: "Dr. APJ Abdul Kalam Technical University",
      desc: "",
    },
    {
      id: 2,
      category: "education",
      icon: "icon-graduation",
      year: "2018 - 2019",
      title: "12th - Higher Secondary School | CBSE ",
      major: "Stream: Science (PCM)",
      grade: "Percentage: 89.8%",
      college: " Heera Singh Pub School, Mathura",
      desc: "",
    },
    {
      id: 3,
      category: "education",
      icon: "icon-graduation",
      year: "2016 - 2017",
      title: "10th - Secondary School | CBSE ",
      major: "",
      grade: "CGPA: 7.0/10",
      college: "Delhi Public School, Mathura",
      desc: "",
    },
    {
      id: 4,
      category: "experience",
      icon: "icon-briefcase",
      year: "Jan'2024 - present",
      title: "Mentor - Open Source Dev",
      company: "Social Winter of Codes 2024",
      desc: "Experienced MERN Stack Developer with a passion for mentoring and guiding aspiring professionals. Proven track record in leading teams and fostering skill development in JavaScript, React, Node.js, and MongoDB. Committed to cultivating a collaborative learning environment at SWOC, ensuring the success and growth of the next generation of developers.",
    },
    {
      id: 5,
      category: "experience",
      icon: "icon-briefcase",
      year: "Nov'2023 - present",
      title: "Technical Content Writer Intern",
      company: "GeeksForGeeks",
      desc: "Produce high-quality technical content, including tutorials and articles covering a wide range of programming languages, Data Structures and Algorithms, web technologies, advanced Java, and popular frameworks and technology topics.",
    },
    {
      id: 6,
      category: "experience",
      icon: "icon-briefcase",
      year: "Nov'2023 - Present",
      title: "SDE Intern",
      company: "RadicalX",
      desc: "Joining RadicalX as an Artificial Intelligence Engineer/Software Engineer, Embracing cutting-edge technologies like OpenAI, Vertex AI and Craft intelligent solutions that empower learners with personalized career guidance and mentorship",
    },
    {
      id: 7,
      category: "experience",
      icon: "icon-briefcase",
      year: "Aug'2023 - Sept'2023",
      title: "Web Developer Intern",
      company: "InternPe",
      desc: " Collaborated on a team that delivered 5 major web development projects within strict deadlines, showcasing adaptability and multitasking abilities ina  fast-paced environment ",
    },
  ];
  

export default Data